version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/book-my-space-db?schema=public
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - .:/src
      - /src/node_modules

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book-my-space-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
